version: '3.7'
networks:
  monitor-net:
    driver: bridge

services:
  influxdb:
    image: influxdb:1.8
    networks:
      - monitor-net
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    networks:
      - monitor-net
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml

  locust-master:
    build: .
    container_name: locust-master
    ports:
      - "8089:8089"
      - "5557:5557"
      - "5558:5558"
    volumes:
      - ./reports:/load/reports
    env_file:
      - .env
      - .env.master
    networks:
      - monitor-net
    entrypoint:
      - locust

  locust-worker:
    build: .
    env_file:
      - .env
      - .env.worker
    networks:
      - monitor-net
    entrypoint:
      - locust
