global:
  scrape_interval:     5s
  evaluation_interval: 15s

alerting:
  alertmanagers:
  - scheme: http

rule_files:
  - 'alerts.yml'

scrape_configs:
  - job_name: 'perf-test'
    static_configs:
    - targets: ['node-exporter:9100']
      labels:
        instance: 'load-generator'
