{
 "title": "Locust",
 "tags": [ "locust" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Success",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"response\" != '404' ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Fail",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND (\"response\" != '200' AND \"response\" != '302')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Totals by HTTP Verb", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "DELETE",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'DELETE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "GET",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'GET'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HEAD",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'HEAD'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "POST",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'POST'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PUT",
   "type": "stat",
   "description": "Total amount of requests done during the time period.",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND \"request_type\" = 'PUT'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Over Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "RPS Over Time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY time(1s), \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Time Over Time",
   "type": "graph",
   "description": "Number of requests per second over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"time\", \"response_time\"\nFROM \"locust_requests\"\nWHERE $timeFilter\nGROUP BY \"request_type\", \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Endpoints",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "$tag_request_type $tag_name",
     "query": "SELECT count(\"response_time\") as \"total requests\", min(\"response_time\") as \"Min (ms)\", max(\"response_time\") as \"Max (ms)\", mean(\"response_time\") as \"Average (ms)\", percentile(\"response_time\", 90) as \"90%ile (ms)\",  percentile(\"response_time\", 95) as \"95%ile (ms)\"  FROM \"locust_requests\" WHERE $timeFilter GROUP BY \"name\", \"request_type\"  "
    }
   ]
  },
  {
   "title": "Errors",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "alias": "$tag_request_type $tag_name: $tag_exception",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"counter\")\nFROM \"locust_requests\"\nWHERE $timeFilter AND exception <> 'None'\nGROUP BY \"request_type\", \"name\", \"exception\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}